### ISSUE TITLE
Introspection XML ends up in lowest, instantiated, object path.

### ISSUE THREAD

**Issue by sensed** [martinhaefner/simppl#21]
Example:
different skeleton objects with paths which builds on each other: "/com", "/com/object1", "/com/object2".

In this case, introspection will only contain the "/com" object. 
Object1 and object2 are dismissed and not contained in the introspection XML.
If i leave the "/com" path unused, I will see both objects in the introspection.

I guess, this problem sources in the independency of the objects to each other, but i find no way to fix this matching the concept of this nice library.

Sure, i could make a special solution to my code, building an XML from my skeleton objects tree, but i think this feature is elementary and should work out of the library.

Do you have an idea?

**Comment by martinhaefner** [comment]
Hi, that's true. The library once was written with no objects in mind. D-Bus came later. So, objects on server are more like "services" rather than objects. For introspection purpose, I could for sure just add some dependency management, but I do not know how this would match with any other D-Bus concepts since I still use it as a more Service-oriented middleware.ffff

**Comment by martinhaefner** [comment]
Ok, hopefully fixed in commit:f326086c1e064a5ce122a3ad22896207d25feb43
